### ISSUE TITLE
Issue with NPM - Windows

### ISSUE THREAD

**Issue by esQmo** [opentrace-community/opentrace-cloud-functions#14]
I'm stuck at the below step:
npm --prefix functions install

**npm ERR! Can't install : Missing package version**

Any help will be appreciated. I'm using Powershell

**Comment by qtangs** [comment]
That script needs to be run from the root folder.
Optionally, you can start at the `functions` folder and run `npm install` instead.

**Comment by esQmo** [comment]
Did both. Still having the issue. First it was complaining about not finding the packages.json, then moved the one located at root/functions/ to /root
