### ISSUE TITLE
Confused with last step

### ISSUE THREAD

**Issue by esQmo** [opentrace-community/opentrace-cloud-functions#16]
I'm refering to this: 
**Download the json credential file and set the path to GOOGLE_APPLICATION_CREDENTIALS environment variable**

Couldn't find it anywhere. I already downloaded the JSON file and I'mnot sure where to put it and where to set the GOOGLE_APPLICATION_CREDENTIALS variable. 

Building on Android

Help appreciated.

**Comment by achrinza** [comment]
`GOOGLE_APPLICATION_CREDENTIALS` is an [environment variable](https://en.wikipedia.org/wiki/Environment_variable). Depending on you operating system, there's different ways to set this value:

## Windows

```powershell
SET /p GOOGLE_APPLICATION_CREDENTIALS=<YOUR_JSON_FILE_NAME.json
```

## Unix

```sh
GOOGLE_APPLICATION_CREDENTIALS=$(cat YOUR_JSON_FILE_NAME.json)
```

(Substitute `YOUR_JSON_FILE_NAME.json` with the JSON filename.

**Comment by achrinza** [comment]
`GOOGLE_APPLICATION_CREDENTIALS` is an [environment variable](https://en.wikipedia.org/wiki/Environment_variable). Depending on the operating system, there's different ways to set this value:

## Windows

```powershell
$env:GOOGLE_APPLICATION_CREDENTIALS="[PATH]"
```

## Unix / macOS

```sh
export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"
```

(Substitute `[PATH]` with the path to the JSON credentials file.)

Further reading:

- https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable

**Comment by esQmo** [comment]
You need to update the Reame file to make it clear to everyone

**Comment by achrinza** [comment]
I’m not part of the team but I’ll see if I can open a PR for review ¯\\\_(ツ)\_/¯

**Comment by esQmo** [comment]
Sorry, not reffering to you explicitly, but to the team. Thanks for your support, appreciate it

**Comment by qtangs** [comment]
Thanks @achrinza.
@esQmo, the README now contains clearer instruction on that.
