### ISSUE TITLE
Unable to firebase login

### ISSUE THREAD

**Issue by dev-vishnupundhir** [opentrace-community/opentrace-cloud-functions#22]
when i am trying the firebase login it will be redirect the
http://localhost:9005/?state=594798400&code=4/ywEwp3M06hnF9-tUtmnHrf-vPxv--UsLvIPK2hY-2WF0htIpJrcAOecUER--TwzDgl2Rq7JJqgtmJNfxG08ONko&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid%20https://www.googleapis.com/auth/cloudplatformprojects.readonly%20https://www.googleapis.com/auth/firebase%20https://www.googleapis.com/auth/cloud-platform&authuser=0&prompt=consent

this page
can you help me.

**Comment by valduze** [comment]
Hi @dev-vishnupundhir 
Copy that link and paste in into your browser to login.
Thanks,
Jongi
