### ISSUE TITLE
Verification Code and PIN usage

### ISSUE THREAD

**Issue by sherinVish14** [opentrace-community/opentrace-cloud-functions#30]
Hi,
It says in Open Trace app, that contact tracer will give the code that should match the verification code shown in the user's Phone(who tested positive). It is not mentioned how the contact tracer will get this code? 

Could anyone explain this?

**Comment by qtangs** [comment]
The PIN is generated by PinGenerator or a subclass of your choice. The result of this is only known by the server so there must be a way for the server to inform the contact tracer. For example, the server can expose an API for the contact tracer to query, or send it in email/SMS to contact tracer as part of an automated workflow. You need to decide what works best for your situation and implement accordingly.

**Comment by sherinVish14** [comment]
Thank you so much.
