### ISSUE TITLE
Use of synchronous crypto.randomBytes() not recommended

### ISSUE THREAD

**Issue by mashbu** [opentrace-community/opentrace-cloud-functions#33]
I believe the use of the synchronous version of crypto.randomBytes() in a server context to generate the IV is not recommended. 
[https://nodejs.org/uk/docs/guides/dont-block-the-event-loop/#blocking-the-event-loop-node-js-core-modules](url)

The synchronous version can block the Event Loop and a malicious actor can repeatedly request TempIDs resulting in a possible DOS attack.

**Comment by qtangs** [comment]
What you're referring to is relevant to the case of a traditional server setup where 1 server (or a cluster of servers) handles all requests. In this case, we're using Cloud Function, each execution is independent of all other executions.

**Comment by mashbu** [comment]
ah that makes sense. thank you.
