### ISSUE TITLE
how to implement processUploadedData 

### ISSUE THREAD

**Issue by cyberman9** [opentrace-community/opentrace-cloud-functions#40]
Please how should the logic for processing the uploaded data be? [code](https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/processUploadedData.ts#L4)

**Comment by qtangs** [comment]
We have shared a reference implementation for `processUploadedData`, you can find the logic here:

https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/processUploadedData.ts#L24
