### ISSUE TITLE
Analyst Uploaded data

### ISSUE THREAD

**Issue by Hoangtho11188** [opentrace-community/opentrace-cloud-functions#42]
Hi, with the uploaded data on Bucket storage, how do we know the phone number(or any info) that connected with our device?
Please find my uploaded data [here](https://github.com/opentrace-community/opentrace-cloud-functions/files/4537452/StreetPassRecord_Xiaomi_Redmi.Note.4X_2020-04-27_08-26-10.json.txt).

And what will we do with this function : _processUploadedData_
Currently it's not implemented yet.

**Comment by qtangs** [comment]
We have shared a reference implementation for processUploadedData, you can find the logic here:

https://github.com/opentrace-community/opentrace-cloud-functions/blob/master/functions/src/opentrace/processUploadedData.ts#L24
