### ISSUE TITLE
Cloud Functions use-case?

### ISSUE THREAD

**Issue by dayaki** [opentrace-community/opentrace-cloud-functions#49]
Thank you for open sourcing the project, been looking to develop something similar to traceTogether for my country.

My question, can this cloud-functions with React Native give me ability to offer same functionality as the traceTogether app?

**Comment by alexissinglaire** [comment]
@dayaki: i believe you should give yourself time to understand how this project works in term of android and cloud functions. Once you manage to understand how they works, then you can find a way how to implement it into technology that you're familiar to. 

Hope it helps.

**Comment by erwanmace** [comment]
@dayaki Cloud Functions (Firebase Cloud Functions) in our case refer to backend API's written in TypeScript (a variation of JavaScript) and running on the Google Firebase platform. You could certainly develop similar API's with different frameworks to run on different environments or platforms but the whole OpenTrace projects relies on Firebase (backend APIs / Cloud Functions, invoking these APIs from the Firebase mobile SDK for iOS and Android, User authentication with OTP)
