### ISSUE TITLE
getUploadToken 401

### ISSUE THREAD

**Issue by supernovahimura** [opentrace-community/opentrace-cloud-functions#52]
Hi, When I want to upload data, the following appears:
![Selección_002](https://user-images.githubusercontent.com/9593923/81763396-c20e2900-9494-11ea-9a9f-bffb65f1b96a.png)

**Comment by alexissinglaire** [comment]
@supernovahimura : hi, HTTP error 401 related with authentication. You can review again your service-account.json that you downloaded from firebase console. 

the good service-account.json contain following components: private_key_id, private_key, auth_uri, token_uri, auth_provider_x509_cert_url, and client_x509_cert_url

good luck.

**Comment by supernovahimura** [comment]
Thanks!!!, I had to repeat the process, I get the following from firebase:
![Selección_006](https://user-images.githubusercontent.com/9593923/81779065-9487a680-94b9-11ea-89bd-732bd714c8ff.png)

Now it asks me for a pin to upload data, how do I get that PIN?

**Comment by alexissinglaire** [comment]
@supernovahimura : refer to below comment on how to hardcode your upload pin inside getUploadToken.ts 

https://github.com/opentrace-community/opentrace-cloud-functions/issues/6#issuecomment-612867291

**Comment by supernovahimura** [comment]
add the following code and it shows me invalid pin, uninstall the app, but now in register your mobile number, nothing returns and nothing appears in firebase, when I select get OTP.
![Selección_007](https://user-images.githubusercontent.com/9593923/81834783-0fc37980-9507-11ea-8b88-08c671672dc6.png)
![Selección_008](https://user-images.githubusercontent.com/9593923/81834895-397ca080-9507-11ea-95f4-3273949e3c75.png)

![changeimagewhats](https://user-images.githubusercontent.com/9593923/81838806-42bc3c00-950c-11ea-906d-968f712f9a64.jpeg)

**Comment by alexissinglaire** [comment]
@supernovahimura : is there any error in the android logcat ? you mean when you press 'Get OTP' there is no error shown in the firebase functions logs?

**Comment by supernovahimura** [comment]
These are the errors I get when debugging the app:
![Selección_010](https://user-images.githubusercontent.com/9593923/81890720-3ff13380-956c-11ea-82e9-9c65e32e8123.png)
![Selección_011](https://user-images.githubusercontent.com/9593923/81890727-467fab00-956c-11ea-8a9d-0f68b34203fc.png)
![Selección_012](https://user-images.githubusercontent.com/9593923/81890738-4d0e2280-956c-11ea-8d37-9217150a6d49.png)
![Selección_013](https://user-images.githubusercontent.com/9593923/81890744-50a1a980-956c-11ea-9b67-30f0e2b66eec.png)
![Selección_014](https://user-images.githubusercontent.com/9593923/81890751-55665d80-956c-11ea-86cf-c1242b75688b.png)

When I press 'Get OTP' I get the following:

![Selección_015](https://user-images.githubusercontent.com/9593923/81890761-5ac3a800-956c-11ea-8f7c-96b3ebaf6865.jpg)
![Selección_016](https://user-images.githubusercontent.com/9593923/81890766-5eefc580-956c-11ea-9a3d-b4a502b48ecb.png)

**Comment by alexissinglaire** [comment]
@supernovahimura : based o your logcat specificlly at the last part, it shows that your app is not authorized to firebase. There are 2  possibilities: 
- the app name you register into firebase project not correct. remember you need to put the value package name (find in manifest file) + stg. e.g your project is io.bluetrace.opentrace therefore you need to register your package name as io.bluetrace.opentrace.stg

- if the approach above still not solving your problem , you can register your debug SHA key inside the android app registration in firebase.

Good luck.

**Comment by supernovahimura** [comment]
thanks @alexissinglaire now it's working
