### ISSUE TITLE
NOT IDLE

### ISSUE THREAD

**Issue by supernovahimura** [opentrace-community/opentrace-cloud-functions#54]
When scanning via bluetooth it fails:
![Selección_022](https://user-images.githubusercontent.com/9593923/81972416-2ab9ea80-95e8-11ea-9241-aff0040279af.png)
![Selección_023](https://user-images.githubusercontent.com/9593923/81972433-30afcb80-95e8-11ea-8d7d-74cfdefb6e59.png)
![Selección_024](https://user-images.githubusercontent.com/9593923/81972449-34435280-95e8-11ea-97c2-5ef32adde4d3.png)

**Comment by sudoharish** [comment]
I m workingon this project on windows my encryption keys part of cloud function test failed,
Active chat on this would resolve it early

**Comment by alexissinglaire** [comment]
@supernovahimura : the error 401 most likely due authorization issue. check your permission for the secret key becoz the getTempID related to secret value in secret manager. double check again the logcat in android studio whether there is any error related to secret key.

Good luck.

**Comment by supernovahimura** [comment]
@alexissinglaire thanks
