### ISSUE TITLE
error:- getting encryption key

### ISSUE THREAD

**Issue by sudoharish** [opentrace-community/opentrace-cloud-functions#55]
i m testing it on windows machine, and generated the key from an online linux terminal by head base64 command. i m not able to know whats the issue, i hope i have given the correct permitions on gcp secret manager.

**_1) config.ts
       #encryption
         should succeed in getting encryption key:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Harish\firebase\opentrace-cloud-functions-master\functions\test\opentrace\config.test.ts)_**

![encyptionerror_cmd](https://user-images.githubusercontent.com/53051422/81988612-63de7300-9659-11ea-9cb3-b3fa972564a3.JPG)
![encr_config](https://user-images.githubusercontent.com/53051422/81988641-6e007180-9659-11ea-84bf-7c66f509e304.JPG)
![encrp_gcp](https://user-images.githubusercontent.com/53051422/81988647-70fb6200-9659-11ea-8bc1-585f668b9683.JPG)

**Comment by alexissinglaire** [comment]
@sudoharish : do you aware your secret key is created using different project id with the one that you run the npm test? please take note if you have multiple project defined in your cloud you need to ensure the usage are in sync.

**Comment by sudoharish** [comment]
@alexissinglaire thanks it was a great help.now all passed just showing delay that can be ignored for now
