### ISSUE TITLE
Unable to generate uploadToken

### ISSUE THREAD

**Issue by harrison-tc** [opentrace-community/opentrace-cloud-functions#6]
It appears that the Firebase and Cloud Functions definition may be incomplete.

How does one go about generating an upload code?

**Comment by harrison-tc** [comment]
Following the instructions, I get: "getUploadToken
Unhandled error TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined", 

If a value is placed into the database under codes->uploadCode->uploadCode, it passes that but fails on checking length.

**Comment by mchmielarski** [comment]
did you use `storeUploadCodes` for inserting to database or maybe you did it directly?

**Comment by harrison-tc** [comment]
It doesn't appear that it's being called. Is there a method I should use on my side to test invoking it?

**Comment by devansh-ramen** [comment]
@mchmielarski 
I called await storeUploadCodes(['1234']); inside getUploadToken.ts class in the getUploadToken to set the PIN and it seems to work fine. I was able to upload data from the App using the PIN 1234

**Comment by harrison-tc** [comment]
That seems to do it, thanks!

**Comment by harrison-tc** [comment]
My mistake

**Comment by rez20004** [comment]
> @mchmielarski
> I called await storeUploadCodes(['1234']); inside getUploadToken.ts class in the getUploadToken to set the PIN and it seems to work fine. I was able to upload data from the App using the PIN 1234

hi sorry, it tried this but does not seems to work. can someone provide some explanation of  where and how to put this in the getUploadToken

**Comment by brianssendagire** [comment]
Hi @rez20004, this will only work after you run `firebase deploy --only functions` and then after add the PIN `1234` in Step 2 and click Upload data. 

I would like however, to generate this code by some function and then send it to the user via SMS and read it automatically. Also processUploadedData() is not implemented yet. Any help going forward with these will be appreciated. Thanks
